const actionTypes = {
  UNSPLASH_INITIALISED: "UNSPLASH_INITIALISED",
  ON_PAGE_LOAD: "ON_PAGE_LOAD",
  SEARCH_QUERY_CHANGED: "SEARCH_QUERY_CHANGED",
  LOAD_MORE_DATA: "lOAD_MORE_DATA",
};

export default actionTypes;
